### ISSUE TITLE
Achievement Conceptualization

### ISSUE THREAD

**Issue by niilolehner** [niilolehner/Team_Awesome#17]
User story:
What is the student's reward for completing his or her assignment?

Achievement concepts:

1. First question answered!
2. 20 questions answered!
3. 50 questions answered!
4. 100 questions answered!
5. 200 questions answered!
6. 500 questions answered!
7. 1000 questions answered!
8. 2000 questions answered!
9. First quiz completed!
10. 4 quizes completed !
11. 8 quizes completed!
12. 16 quizes completed!
13. 40 quizes completed!
14. 80 quizes completed!
15. 160 quizes completed!
16. 320 quizes completed!
17. Lightning (completed a quiz in under X minutes, 100% correctly)
18. Perfect Snail (took over X minutes to complete a quiz, 100% correctly)
19. Sad Panda (completed a quiz 100% wrongly)
20. Cookie Monster (secret achievement, a teacher can grant it)
21. Marathon (got all other achievements)

**Comment by MallaMalla** [comment]
achievements earned in learning mode
