### ISSUE TITLE
Teacher feedback

### ISSUE THREAD

**Issue by MallaMalla** [niilolehner/Team_Awesome#22]
User story:
How could the teacher react to be seen on the student side that the teacher has seen it (Teacher Feedback)?

**Comment by MallaMalla** [comment]
From "popUp" teacher can choose one of the many premade feedbacks

**Comment by MallaMalla** [comment]
feedback for example
"harjoittele enemmän casual-modessa"
"alat suoriutua hyvin!"
"uskalla koittaa reagoida nopeammin"
"keskity!"

**Comment by Aesmou** [comment]
Feature:
How could the teacher react to be seen on the student side that the teacher has seen it (Teacher Feedback).

**Comment by Aesmou** [comment]
Created "hamburger" model.

**Comment by Aesmou** [comment]
Created 3 section feedback fields and cookiemonster checbox.

**Comment by Aesmou** [comment]
Deleted score ID from table and table order to date.
