### ISSUE TITLE
Refactoring, round 2

### ISSUE THREAD

**Issue by niilolehner** [niilolehner/Team_Awesome#55]
There is a lot of repetition and redundancy in achievements.js, specifically in the checkAndAwardAchievs function. Sub-functions with appropriate parameter fields could be set up to avoid said repetition. Certain variables could also be made to not repeat those identical function parameters. There also seems to be a problem when for example a student has no achievements yet, because unlocked achievements have to be checked before JS knows which achievements to test unlocking conditions for. In other words it's possible that a Database SQL query for studentachievements returns empty, and therefore an empty JSON/array gets returned. Lines for this case have to be created.

DONE FOR NOW.

**Comment by Aesmou** [comment]
Included script-tags to specific pages.
