### ISSUE TITLE
Create HTML view to teacher

### ISSUE THREAD

**Issue by MallaMalla** [niilolehner/Team_Awesome#9]

**Comment by Aesmou** [comment]
- It is recommended to use references, not repetition.
- Responsiveness important.
- Management is mainly on a computer, and use on a mobile device.

**Comment by Aesmou** [comment]
Created HTML-structure with dummy-information.

**Comment by Aesmou** [comment]
Redo HTML-structure to Modal form with "hamburger"-style

**Comment by Aesmou** [comment]
View done
